### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by hecko** [DuyTrandeLion/nrf52-ssd1309#1]
Will trhis driver be available in the near future? :)

**Comment by DuyTrandeLion** [comment]
Hello hecko,
> Will trhis driver be available in the near future? :)

=> Yes, due to some issues during my discussion with the customer so I was not allowed to release earlier. You can drop an email to lowe.tran@gmail.com to get the library or you can wait a few more days for me to publish the library online.

Also sorry for my late reply.

Best regards,
    Duy

**Comment by hecko** [comment]
Thanks Duy, i have already written the driver myself ;)

**Comment by DuyTrandeLion** [comment]
Glad to hear that!! Good luck bro!
